spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    url: jdbc:postgresql://postgres:5432/certificate
    username: postgres
    hikari:
      maximum-pool-size: 20
  jpa:
    show-sql: true
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 50
  liquibase:
    change-log: db.changelog-master.yaml
    enabled: false

