spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    url: jdbc:postgresql://127.0.0.1:5432/certificate
    username: postgres
    hikari:
      maximum-pool-size: 20
  jpa:
    show-sql: true
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 50
